services:
  - type: web
    name: flight-sim-server
    rootDir: server
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: "https://<YOUR-STATIC>.onrender.com,http://localhost:5173"
    healthCheckPath: "/health"
    autoDeploy: true

  - type: static
    name: flight-sim-client
    rootDir: client
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
    envVars:
      - key: VITE_SERVER_URL
        value: "https://<YOUR-SERVER>.onrender.com"
      - key: VITE_TERRAIN_PROVIDER
        value: "none"
